#!/bin/bash
# coturn_installer.sh - Step-by-step interactive installer for coturn (TURN server)
# Use for Personal Meet on local network. Run on the machine that will run coturn.

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "=============================================="
echo "  Personal Meet - Coturn (TURN) installer"
echo "=============================================="
echo ""

# --- Step 1: Check root ---
echo "[Step 1/8] Checking privileges..."
if [ "$(id -u)" -ne 0 ]; then
  echo "This script needs root to install packages and write config."
  echo "Run: sudo $0"
  exit 1
fi
echo "OK. Running as root."
echo ""

# --- Step 2: Detect package manager and install coturn ---
echo "[Step 2/8] Installing coturn..."
if command -v apt-get &>/dev/null; then
  apt-get update -qq
  apt-get install -y coturn
  TURN_CONF="/etc/turnserver.conf"
elif command -v dnf &>/dev/null; then
  dnf install -y coturn
  TURN_CONF="/etc/coturn/turnserver.conf"
elif command -v yum &>/dev/null; then
  yum install -y epel-release 2>/dev/null || true
  yum install -y coturn
  TURN_CONF="/etc/coturn/turnserver.conf"
else
  echo "Unsupported OS. Install coturn manually and configure with this script's config."
  exit 1
fi
echo "Coturn installed. Config path: $TURN_CONF"
echo ""

# --- Step 3: Choose listening IP ---
echo "[Step 3/8] TURN listening address"
echo "  Use 0.0.0.0 to listen on all interfaces (typical for one server)."
echo "  Or enter this server's IP if you want to bind only to it."
read -r -p "Listening IP [0.0.0.0]: " LISTEN_IP
LISTEN_IP="${LISTEN_IP:-0.0.0.0}"
echo "Using: $LISTEN_IP"
echo ""

# --- Step 4: External / relay IP (for clients to reach TURN) ---
echo "[Step 4/8] Server IP or hostname that clients will use to connect"
echo "  (e.g. this machine's LAN IP like 192.168.1.10, or hostname)"
read -r -p "Server IP or hostname: " SERVER_IP
if [ -z "$SERVER_IP" ]; then
  echo "Server IP is required. Exiting."
  exit 1
fi
read -r -p "TURN port [3478]: " TURN_PORT
TURN_PORT="${TURN_PORT:-3478}"
echo "Clients will use: turn:${SERVER_IP}:${TURN_PORT}"
echo ""

# --- Step 5: TURN credentials ---
echo "[Step 5/8] TURN authentication (long-term credentials)"
read -r -p "TURN username [meet]: " TURN_USER
TURN_USER="${TURN_USER:-meet}"
read -r -s -p "TURN password: " TURN_PASS
echo ""
if [ -z "$TURN_PASS" ]; then
  TURN_PASS=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64)
  echo "Generated random password (save it): $TURN_PASS"
fi
echo ""

# --- Step 6: Write turnserver.conf ---
echo "[Step 6/8] Writing coturn config..."

# Backup if exists
if [ -f "$TURN_CONF" ]; then
  cp "$TURN_CONF" "${TURN_CONF}.bak.$(date +%Y%m%d%H%M%S)"
fi

# Ensure config dir exists (e.g. /etc/coturn)
mkdir -p "$(dirname "$TURN_CONF")"

cat > "$TURN_CONF" << EOF
# Personal Meet - coturn config (generated by coturn_installer.sh)
listening-ip=$LISTEN_IP
listening-port=$TURN_PORT
relay-ip=$SERVER_IP
external-ip=$SERVER_IP
realm=personal.meet
lt-cred-mech
user=$TURN_USER:$TURN_PASS
no-multicast-peers
no-cli
EOF
echo "Written: $TURN_CONF"
echo ""

# --- Step 7: Enable and start coturn ---
echo "[Step 7/8] Enabling and starting coturn..."
if [ -f /etc/default/coturn ]; then
  sed -i 's/^#*TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/default/coturn 2>/dev/null || true
  echo "TURNSERVER_ENABLED=1" >> /etc/default/coturn 2>/dev/null || true
fi
systemctl enable coturn 2>/dev/null || true
systemctl restart coturn 2>/dev/null || true
sleep 1
if systemctl is-active --quiet coturn 2>/dev/null; then
  echo "Coturn is running."
else
  echo "Warning: coturn may not have started. Check: systemctl status coturn"
fi
echo ""

# --- Step 8: Write turn-config.json for meet.js ---
echo "[Step 8/8] Writing ICE config for Personal Meet (meet.js)..."
OUTPUT_JSON="$SCRIPT_DIR/turn-config.json"
# Protocol: use turn: and stun: with same host so clients on same LAN can use both
cat > "$OUTPUT_JSON" << EOF
{
  "iceServers": [
    { "urls": "stun:${SERVER_IP}:${TURN_PORT}" },
    {
      "urls": "turn:${SERVER_IP}:${TURN_PORT}",
      "username": "$TURN_USER",
      "credential": "$TURN_PASS"
    }
  ]
}
EOF
chmod 644 "$OUTPUT_JSON"
echo "Written: $OUTPUT_JSON"
echo ""

echo "=============================================="
echo "  Installation complete"
echo "=============================================="
echo ""
echo "1. Copy $OUTPUT_JSON to the machine running Personal Meet (server.js)"
echo "   so it sits next to server.js (project root)."
echo "2. Restart the Node server. meet.js will use GET /api/ice-servers to get TURN/STUN."
echo "3. Open firewall if needed:"
echo "   ufw allow $TURN_PORT/udp"
echo "   ufw allow $TURN_PORT/tcp"
echo "   ufw reload"
echo ""
echo "TURN URI: turn:${SERVER_IP}:${TURN_PORT}"
echo "Username: $TURN_USER"
echo "Password: (saved in $OUTPUT_JSON - keep it secret)"
echo ""
